language: python
python:
#  - "2.7"
  - "3.6"
cache: pip

install:
  - pip install tensorflow
  - pip install google-api-python-client oauth2client
  - pip install -e .
script:
  - pytest -v UTest/correlation_test.py UTest/dataset_test.py UTest/virtualfile_test.py
  - pytest -v UTest/image_test.py
  - pytest -v UTest/loader_test.py
  - pytest -v UTest/motion_test.py
  - pytest -v UTest/noise_test.py
  - pytest -v UTest/vgg_test.py
  - bash UTest/training_test.sh
